# Resolución de sistemas

- Para resolver sistemas usaremos el paquete ${\tt Numpy}$
- Para realizar ciertas operaciones con las matrices hay que usar el paquete ${\tt linalg}$ de ${\tt Numpy}$
- Definimos un vector 1d y una matriz $m\times n$ vía el método ${\tt array}$
- Para definir un array 1d basta indicar los términos en una lista 
- Para crear una matriz empleamos una lista de listas, donde cada lista interna contiene una fila de la matriz

- Vamos a crear la matriz $A$ y el vector $b$, 

$$
A=\left( \begin{array}{ccc}
3& 0 & 2 \\ 2& 0 & -2 \\ 0  & 1 & 1
\end{array}\right),
\quad
b=\left(\begin{array}{l}
1 \\ 2 \\ 4
\end{array}\right)
$$

In [1]:
import numpy as np
A=np.array([ [3, 0, 2], [2, 0, -2], [0, 1, 1] ])
print("A = \n ", A)

b=np.array( [1, 2, 4] )
print("b = \n ", b)


A = 
  [[ 3  0  2]
 [ 2  0 -2]
 [ 0  1  1]]
b = 
  [1 2 4]


- Podemos calcular el rango de una matriz, su traza, su determinante, la matriz traspuesta y la matriz inversa (si la hay). 
- Para alguna de estas operaciones necesitamos usar métodos de la librería ${\tt linalg}$ de ${\tt Numpy}$

In [2]:
import numpy.linalg as la #asociamos el alias la

rango=la.matrix_rank(A) #rango de la matriz
print("rango= ", rango)

traza=np.trace(A) #traza
print("Traza= ", traza)

det=la.det(A) #determinante
print("Determinante= ", det)

At=A.T
print("Traspuesta de A:\n", At)

Ai=la.inv(A)
print("Inversa de A: ", Ai)

rango=  3
Traza=  4
Determinante=  10.0
Traspuesta de A:
 [[ 3  2  0]
 [ 0  0  1]
 [ 2 -2  1]]
Inversa de A:  [[ 0.2  0.2  0. ]
 [-0.2  0.3  1. ]
 [ 0.2 -0.3  0. ]]


- Podemos sumar matrices o multiplicarlas por un escalar

In [4]:
C= A + A
print ("A + A = \n", A)
C= 3*A #multiplica todos los elementos de A por 3
print()
print (" 3*A= \n", C)

A + A = 
 [[ 3  0  2]
 [ 2  0 -2]
 [ 0  1  1]]

 3*A= 
 [[ 9  0  6]
 [ 6  0 -6]
 [ 0  3  3]]


- Podemos multiplicar una matriz por un vector o una matriz por otra. 
- Para ellos podemos empelar el operador ${\tt @}$ o la función $\verb|dot|$

In [6]:
#matriz por vector

w=A@b
print("A@b= ", A@b)
w=np.dot(A,b)

#Matriz por matriz

Ai=la.inv(A)

B=A@Ai
print("A@Ai= \n", B)

C=np.dot(A,Ai)
print("np.dot(A,Ai)= \n", C)

A@b=  [11 -6  6]
A@Ai= 
 [[  1.00000000e+00   0.00000000e+00   0.00000000e+00]
 [ -5.55111512e-17   1.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   1.00000000e+00]]
np.dot(A,Ai)= 
 [[  1.00000000e+00   0.00000000e+00   0.00000000e+00]
 [ -5.55111512e-17   1.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   1.00000000e+00]]


- Mediante el operador $\verb|*|$ multiplicamos los arrays componente a componente

In [7]:
B=A*Ai
print("A*Ai= \n ", B)

A*Ai= 
  [[ 0.6  0.   0. ]
 [-0.4  0.  -2. ]
 [ 0.  -0.3  0. ]]


- Para resolver un sistema lineal se emplea el método $\verb|solve|$ de ${\tt Numpy}$
- Calculamos la solución del sistema $A\cdot X= b$:
$$
\left( \begin{array}{ccc}
3& 0 & 2 \\ 2& 0 & -2 \\ 0  & 1 & 1
\end{array}\right)
\left(\begin{array}{l}
x \\ y \\ z
\end{array}\right)
=
\left(\begin{array}{l}
1 \\ 2 \\ 4
\end{array}\right)
$$

In [8]:
v=la.solve(A,b)
print("Sol del sist. = ", v)

Sol del sist. =  [ 0.6  4.4 -0.4]


# Cálculo de autovalores y autovectores

- Para calcular los autovalores y autovectores de una matriz usaremos el método $\verb|eig|$ de la librería ${\tt linag}$ de ${\tt Numpy}$ 

- Calculares los autovalores y autovectores de la matriz:


$$
A=\left( \begin{array}{ccc}
3& 1 & 0 \\ 2& 2 & 0 \\ 0  & 0 & 8
\end{array}\right)
$$

In [9]:
A=np.array([ [3,1,0], [2,2,0], [0,0,8] ])
w,v=la.eig(A)
print("Autovalores= \n", w)
print("Autovectores \n", v)

Autovalores= 
 [ 4.  1.  8.]
Autovectores 
 [[ 0.70710678 -0.4472136   0.        ]
 [ 0.70710678  0.89442719  0.        ]
 [ 0.          0.          1.        ]]


- A partir de los autovalores y autovectores, podemos construir la matriz diagonal $D$ y la matriz de paso $P$, que verifica $A=P^{-1}D P$
- El método $\verb|diag|$ construye una matriz diagonal a partir de un vector
- El método $\verb|vstack|$ construye una matriz a partir de vectores. Cada vector lo sitúa en una fila

In [10]:
D=np.diag(w) #construye una matriz diagonal a partir del vector w
print ("D= \n",D)

P=np.vstack([v[0], v[1], v[2]])  #cada final es uno de los autovectores
print("P=\n",P)

P=P.T

print("P=\n",P)
Pi=la.inv(P)

I=A-Pi@D@P
print("A-Pi*D*P=\n",I )

D= 
 [[ 4.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  8.]]
P=
 [[ 0.70710678 -0.4472136   0.        ]
 [ 0.70710678  0.89442719  0.        ]
 [ 0.          0.          1.        ]]
P=
 [[ 0.70710678  0.70710678  0.        ]
 [-0.4472136   0.89442719  0.        ]
 [ 0.          0.          1.        ]]
A-Pi*D*P=
 [[ -4.44089210e-16  -1.00000000e+00   0.00000000e+00]
 [  1.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00]]
