In [3]:
import numpy as np
import numpy.linalg as lg
A=np.array( [ [1,2], [2,1] ] )
l,P=lg.eig(A)
print("autovalores= ", l)
print("autovectores ",P) # Las columnas son los autovectores. Nos dan la matriz de paso
D=np.diag(l)
M= A - P@D@lg.inv(P)
print(M)

autovalores=  [ 3. -1.]
autovectores  [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
[[ -1.11022302e-15   2.22044605e-16]
 [  0.00000000e+00   1.11022302e-16]]


In [5]:
l1,l2=l
v1=P[:,0]
v2=P[:,1]
print( A@v1 - l1*v1)
print( A@v2 - l2*v2)


[ -4.44089210e-16   0.00000000e+00]
[  7.77156117e-16   1.11022302e-16]


- Ejr de una matriz de Leslie


In [10]:
A=np.array([[0,6,3],[17/100., 0, 0],[0,24./100., 5/100.] ]  )
l,P=lg.eig(A)
print("Autovalores= ", l)
print( "P= ", P)
D=np.diag(l)
M= A - P@D@lg.inv(P)
print(M)

Autovalores=  [ 1.06782775 -0.94723866 -0.07058909]
P=  [[-0.98688539  0.98338607  0.18326724]
 [-0.15711384 -0.17648734 -0.44136324]
 [-0.03704686  0.04247425  0.87841426]]
[[  4.87565717e-16   2.66453526e-15   8.88178420e-16]
 [  0.00000000e+00   3.75676053e-16   6.93889390e-17]
 [  1.08420217e-17   1.66533454e-16   5.55111512e-17]]


In [13]:
v1=P[:,0]
v2=P[:,1]
v3=P[:,2]
print(A@v1-l[0]*v1)
print(A@v2-l[1]*v2)
print(A@v3-l[2]*v3)

[ -8.88178420e-16  -8.32667268e-17  -3.46944695e-17]
[  2.22044605e-16  -5.55111512e-17  -6.93889390e-18]
[  7.28583860e-17  -1.11022302e-16  -6.93889390e-18]


In [12]:
#Evolución para cualquier instante de tiempo "tk"
b=np.array([0,100,0])
c=lg.inv(P)@b
print(c)
#tb podríamos hacer
c=lg.solve(P,b)
print(c)

[-301.55766845 -302.99089355    1.93251167]
[-301.55766845 -302.99089355    1.93251167]


In [14]:
k=20
Ek= c[0]*(l[0]**k)*v1 + c[1]*(l[1]**k)*v1 +c[2]*(l[2]**k)*v1 
print(Ek)

[ 1206.89177475   192.13923       45.30571621]


In [16]:
#Para un k suficientemente grande
#El autovalor dominante es el primero, l[0]

k=500
Ek= c[0]*(l[0]**k)*v1 
print(Ek)

[  5.29954471e+16   8.43696561e+15   1.98940513e+15]


- Otro ejercicio de la matriz de Leslie

In [21]:
A= np.array( [[0, 80./100, 50./100],[60./100, 0, 0],[0,85/100, 0] ] )
E0=np.array( [100, 60,50] )
for k in range(0, 4):
    Ek= A @ E0
    E0=Ek
    print(Ek)

[ 73.  60.  51.]
[ 73.5  43.8  51. ]
[ 60.54  44.1   37.23]
[ 53.895  36.324  37.485]


In [22]:
import numpy.linalg as lg
l,P=lg.eig(A)
print("autovalores= ", l)

autovalores=  [ 0.87778377+0.j         -0.43889188+0.31285501j -0.43889188-0.31285501j]


In [23]:
print( np.abs(l)) #calculamos el modulo.. El primer autovalor es el dominante

[ 0.87778377  0.53898455  0.53898455]


In [24]:
l1=l[0].real
print(l1)

0.877783769562
